[build]
  functions = "functions"
  publish = "public"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/vless/*"
  to = "/.netlify/functions/vless/:splat"
  status = 200
  force = true