[build]
  publish = "public"
  functions = "functions"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["ws"]

[build.environment]
  NODE_VERSION = "18"
  # DEBUG = "*"  # 生产环境中建议删除或设置更具体的值

[dev]
  framework = "#static"
  targetPort = 8888
  port = 8888
  publish = "public"
  autoLaunch = false
  debug = true

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
