[build]
  publish = "public"
  functions = "functions"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  external_node_modules = ["ws"]

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/vless"
  status = 200
  force = true
  conditions = {Path = "/.netlify/functions/vless"}

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200